"""Generate frontend/src/lib/shapes.ts from the generator geometry so answer icons match the puzzle.

Usage: python scripts/gen_shapes_ts.py <path/to/pact_core_dir_or_reference_dir> <out.ts>
Checks each icon against mdg.inside_shape by rasterised IoU (must be >= 0.97).
"""

import math
import os
import sys

HERE_MDG = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[2] if len(sys.argv) > 2 else "shapes.ts"
sys.path.insert(0, HERE_MDG)
import mdg  # noqa: E402


def fmt(v: float) -> str:
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def poly_path(pts) -> str:
    return "M " + " L ".join(f"{fmt(x)} {fmt(y)}" for x, y in pts) + " Z"


def boundary_by_rays(name: str, cu: float, cv: float, n: int = 144):
    pts = []
    for k in range(n):
        a = 2 * math.pi * k / n
        dx, dy = math.cos(a), math.sin(a)
        lo, hi = 0.0, 2.0
        for _ in range(40):
            mid = (lo + hi) / 2
            if mdg.inside_shape(name, cu + dx * mid, cv + dy * mid):
                lo = mid
            else:
                hi = mid
        pts.append((cu + dx * lo, cv + dy * lo))
    return pts


def moon_polygon():
    r1, (bx, by), r2 = 0.85, (0.42, -0.12), 0.66
    outer = [(r1 * math.cos(t), r1 * math.sin(t)) for t in (2 * math.pi * k / 720 for k in range(720))]
    outer = [p for p in outer if (p[0] - bx) ** 2 + (p[1] - by) ** 2 > r2 * r2]
    gaps = [i for i in range(len(outer)) if math.dist(outer[i - 1], outer[i]) > 0.05]
    if gaps:
        outer = outer[gaps[0] :] + outer[: gaps[0]]
    inner = [(bx + r2 * math.cos(t), by + r2 * math.sin(t)) for t in (2 * math.pi * k / 720 for k in range(720))]
    inner = [p for p in inner if p[0] ** 2 + p[1] ** 2 <= r1 * r1]
    gaps = [i for i in range(len(inner)) if math.dist(inner[i - 1], inner[i]) > 0.05]
    if gaps:
        inner = inner[gaps[0] :] + inner[: gaps[0]]
    if math.dist(outer[-1], inner[0]) > math.dist(outer[-1], inner[-1]):
        inner = inner[::-1]
    return (outer + inner)[::6]


def polygons():
    r, s = 0.82, 0.72
    return {
        "circle": [(r * math.cos(2 * math.pi * k / 180), r * math.sin(2 * math.pi * k / 180)) for k in range(180)],
        "square": [(-s, -s), (s, -s), (s, s), (-s, s)],
        "triangle": list(mdg._TRIANGLE),
        "star": list(mdg._STAR),
        "plus": [
            (-0.3, -0.9),
            (0.3, -0.9),
            (0.3, -0.3),
            (0.9, -0.3),
            (0.9, 0.3),
            (0.3, 0.3),
            (0.3, 0.9),
            (-0.3, 0.9),
            (-0.3, 0.3),
            (-0.9, 0.3),
            (-0.9, -0.3),
            (-0.3, -0.3),
        ],
        "heart": boundary_by_rays("heart", 0.0, 0.2),
        "arrow": list(mdg._ARROW),
        "moon": moon_polygon(),
    }


def point_in_poly(x, y, poly):
    return mdg._pip(x, y, tuple(poly))


def iou(name, poly, n=200):
    inter = uni = 0
    for j in range(n):
        for i in range(n):
            u, v = (i + 0.5) * 2 / n - 1, (j + 0.5) * 2 / n - 1
            a, b = mdg.inside_shape(name, u, v), point_in_poly(u, v, poly)
            inter += a and b
            uni += a or b
    return inter / uni


def main() -> int:
    polys = polygons()
    paths = {name: poly_path(p) for name, p in polys.items()}
    r = 0.82
    paths["circle"] = f"M -{r} 0 A {r} {r} 0 1 0 {r} 0 A {r} {r} 0 1 0 -{r} 0 Z"
    labels = {
        "circle": "Circle",
        "square": "Square",
        "triangle": "Triangle",
        "star": "Star",
        "plus": "Plus",
        "heart": "Heart",
        "arrow": "Arrow",
        "moon": "Crescent moon",
    }
    for name in mdg.SHAPES:
        score = iou(name, polys[name])
        print(f"{name:9} IoU={score:.3f}")
        if score < 0.97:
            print(f"ERROR: icon for {name} does not match generator geometry", file=sys.stderr)
            return 1
    lines = [
        "// Shape icons for the PACT answer buttons.",
        "// GENERATED by scripts/gen_shapes_ts.py from pact_core/mdg.py geometry. Do not hand-edit.",
        '// viewBox="-1 -1 2 2", +y points down (same convention as the canvas).',
        "export const SHAPE_IDS = [" + ", ".join(f'"{s}"' for s in mdg.SHAPES) + "] as const;",
        "export type ShapeId = (typeof SHAPE_IDS)[number];",
        "",
        "export const SHAPE_LABELS: Record<ShapeId, string> = {",
        *[f'  {s}: "{labels[s]}",' for s in mdg.SHAPES],
        "};",
        "",
        "export const SHAPE_PATHS: Record<ShapeId, string> = {",
        *[f'  {s}:\n    "{paths[s]}",' for s in mdg.SHAPES],
        "};",
        "",
        "export function isShapeId(value: string): value is ShapeId {",
        "  return (SHAPE_IDS as readonly string[]).includes(value);",
        "}",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
